kubeconfig:
  file: "kc.yaml"      # Path to kubeconfig file of the cluster that hosts knative
db:
  user: "fastpath"     # User Name
  password: "fastpath" # Password
  name: "fastpath"     # Name of Database
  host: "localhost"    # Host IP or URL on which mysql DB is hosted
  port: "3306"         # DB port
constraints:
  max-scale: "3"       # Constraint on replica count
  max-app: "7"         # Constraint on maximum apps deploy count
jwks:
  url: "jwks-url"      # JWKS url of auth0 tenant.
auth:
  client-id: "auth0-client-id" #Auth0 client-id of tenant.
